#!/bin/bash -eu

shellscripts() {
  for i in $(echo ${PATH//:/ }); do
    pushd $i
    file * 2>/dev/null
    popd 
  done |
  grep shell |
  wc -l
}

commands() {
  for i in $(echo ${PATH//:/ }); do
    pushd $i
    file * 2>/dev/null
    popd 
  done |
  wc -l
}

pct=$(echo "100*$(shellscripts)/$(commands)" | bc -l)
printf "%2.4s%% of the executables in \$PATH are shell scripts\n" $pct
